//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Raid
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Nazwa jest wymagana", AllowEmptyStrings = false)]
        public string Nazwa { get; set; }
        public int LokacjaId { get; set; }
        public int TypId { get; set; }
    
        public virtual Lokacja Lokacja { get; set; }
        public virtual Typ Typ { get; set; }
    }
}
